WR366016: Plugin update
catalyst/moodle-search_postgresfulltext pull request #7
Opened 2022-01-05 03:33 UTC by sumaiyamannan

Hi Alex,

I have included performance patch from otagopoly as requested in the WR. This includes:
- search_postgresfulltext: fixed error in previous optimisation
- search_postgresfulltext: additional optimisation
- search_postgresfulltext: fixed sql error
- search_postgresfulltext: Optimised search query

I have also tested this change by deploying it on victoria-testing-moodle, followed by a quick functional test on the site. Once this is merged, I will deploy it on our local branches. 

Regards,

Sumaiya

2022-01-10 23:07 UTC, alexmorrisnz requested changes

2022-01-10 23:07 UTC, alexmorrisnz commented on classes/engine.php
> +        $fileparams = array();
`$join`, `$fileands` and `$fileparams` are all unused here, they can be removed.

2022-01-10 23:07 UTC, alexmorrisnz commented on classes/engine.php
> +        $fileparams = array();
Same with `$countselect` and `$fullselect` above

2022-01-11 02:47 UTC, sumaiyamannan commented on classes/engine.php
> +        $fileparams = array();
this is done

2022-01-11 22:46 UTC, alexmorrisnz approved these changes

2022-01-11 22:47 UTC, merged